name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ github.workflow }}-latest
    strategy:
      matrix:
        ruby: [ 'head', '3.0' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: gem install rake-compiler --no-document
    - name: Run test
      run: rake
